---
- hosts: ibm
  tasks:
    - name: Put ssh key in authorized hosts
      shell: echo "{{ pub_shh_key }}" >> ~/.ssh/authorized_keys

    - name: "Download Apache"
      yum:
        name: httpd
        state: latest
      become: yes

    - name: "Enable Apache"
      service:
        name: httpd
        state: started
      become: yes

    - name: "Download Web Page"
      shell: echo "Medium" > /var/www/html/index.html
      become: yes
