- hosts: localhost
  gather_facts: false
  tasks:
    - name: Log into OCP
      shell: oc get PlacementRule -A
      register: output
     
    - debug:
        msg: "{{ output.stdout_lines }}"
      
