
- hosts: localhost
  gather_facts: false
  tasks:
    - name: get kubectl
      shell: curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
    
    - name: install kubectl
      shell: chmod +x ./kubectl
      
    - name: Log into OCP
      shell: cat "{{ kubeconifg }}"
      register: output
     
    - debug:
        msg: "{{ output.stdout_lines }}"
        
 #   - name: Log into OCP
 #     shell: kubectl create configmap NAME [--from-file=[key=]source] [--from-literal=key1=value1] [--dry-run=server|client|none]
