
- hosts: localhost
  gather_facts: false
  tasks:
    - shell: echo "{{ kubeconifg }}"
      register: output
     
    - debug:
        msg: "{{ output.stdout_lines }}"
  
    - name: get kubectl
      shell: curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
    
    - name: install kubectl
      shell: chmod +x ./kubectl
      
    - name: Log into OCP
      shell: echo "{{ kubeconifg }}" > kubeconfig && export KUBECONFIG=./kubeconfig
     
    - name: Create Configmap
      shell: ./kubectl create configmap demo-configmap --from-literal=installed-by-mcm=true --from-literal=configured-by-ansible=true
        
