
- hosts: localhost
  gather_facts: false
  tasks:
    - name: get kubectl
      shell: curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
    
    - name: install kubectl
      shell: chmod +x ./kubectl
      
    - name: Log into OCP
      shell: echo "{{ kubeconfig }}" | base64 -d > kubeconfig && export KUBECONFIG=./kubeconfig
     
    - name: Set Context
      shell: ./kubectl config set-context test-iks-cluster --cluster=test-iks-cluster --namespace=default
 
    - name: Run example kubectl command
      shell: ./kubectl config use-context test-iks-cluster
      register: output
     
    - debug:
        msg: "{{ output.stdout_lines }}"
   
    - name: Run example kubectl command
      shell: ./kubectl config get-contexts
      register: output
     
    - debug:
        msg: "{{ output.stdout_lines }}"
        
    - name: Run example kubectl command
      shell: ./kubectl get pods
      register: output
     
    - debug:
        msg: "{{ output.stdout_lines }}"
